core/routes/web.php
    Route::post('authorize-net', 'AuthorizeNet\ProcessController@ipn')->name('AuthorizeNet');
    Route::post('2check-out', 'TwoCheckOut\ProcessController@ipn')->name('TwoCheckOut');
    Route::post('mercado-pago', 'MercadoPago\ProcessController@ipn')->name('MercadoPago');
});

// User Support Ticket
Route::prefix('ticket')->group(function () {
    Route::get('/', 'TicketController@supportTicket')->name('ticket');
    Route::get('/new', 'TicketController@openSupportTicket')->name('ticket.open');
    Route::post('/create', 'TicketController@storeSupportTicket')->name('ticket.store');
    Route::get('/view/{ticket}', 'TicketController@viewTicket')->name('ticket.view');
    Route::post('/reply/{ticket}', 'TicketController@replyTicket')->name('ticket.reply');
    Route::get('/download/{ticket}', 'TicketController@ticketDownload')->name('ticket.download');
});


/*
|--------------------------------------------------------------------------
| Start Admin Area
|--------------------------------------------------------------------------
*/

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {

    Route::namespace('Auth')->group(function () {
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login')->name('loginPost');
        Route::get('logout', 'LoginController@logout')->name('logout');
        // Admin Password Reset
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
        Route::post('password/reset', 'ForgotPasswordController@sendResetCodeEmail');
        Route::post('password/verify-code', 'ForgotPasswordController@verifyCode')->name('password.verify.code');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset.form');
        Route::post('password/reset/change', 'ResetPasswordController@reset')->name('password.change');
    });




    // Todo refactor it to controller
    Route::middleware('admin')->group(function () {

        // General Settings
        Route::prefix("settings")->name("settings.")->group(function () { // Note the dot after "settings" in name()

            Route::get("theme_settings", 'SiteThemeSettingController@index')->name("theme_settings");
            Route::post("theme_settings", 'SiteThemeSettingController@update')->name("theme_settings.update");

            Route::get("site_settings", 'SiteSettingController@index')->name("site_settings");
            Route::post("site_settings", 'SiteSettingController@update')->name("site_settings.update");

        });
        Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
        Route::get('exchange', 'AdminController@get_exchange_rate')->name('exchange');
        Route::get('exchange/index', 'AdminController@exchange_index')->name('exchange.index');
        Route::get('profile', 'AdminController@profile')->name('profile');
        Route::post('profile', 'AdminController@profileUpdate')->name('profile.update');
        Route::get('password', 'AdminController@password')->name('password');
        Route::post('password', 'AdminController@passwordUpdate')->name('password.update');
        //export
        Route::get('export', 'ExportController@BidExport')->name('bid.history.export');
        Route::get('export/{id}', 'ExportController@ProductBidExport')->name('product.bid.export');
        //Notification
        Route::get('notifications', 'AdminController@notifications')->name('notifications');
        Route::get('notification/read/{id}', 'AdminController@notificationRead')->name('notification.read');
        Route::get('notifications/read-all', 'AdminController@readAll')->name('notifications.readAll');

        //Report Bugs
        Route::get('request-report', 'AdminController@requestReport')->name('request.report');
        Route::post('request-report', 'AdminController@reportSubmit');

        Route::get('system-info', 'AdminController@systemInfo')->name('system.info');

        //Manage Category
        Route::get('categories', 'CategoryController@index')->name('categories');
        Route::post('category/store/{id?}', 'CategoryController@saveCategory')->name('category.store');


        //Manage Product
        Route::get('products/all', 'ProductController@index')->name('product.index');
        Route::get('products/live', 'ProductController@index')->name('product.live');
        Route::get('products/pending', 'ProductController@index')->name('product.pending');
        Route::get('products/upcoming', 'ProductController@index')->name('product.upcoming');
        Route::get('products/expired', 'ProductController@index')->name('product.expired');
        Route::post('approve-product', 'ProductController@approve')->name('product.approve');
        Route::get('products/add/{id?}', 'ProductController@create')->name('product.create');
        Route::post('store-product', 'ProductController@store')->name('product.store');
        Route::get('product/edit/{id}', 'ProductController@edit')->name('product.edit');
        Route::get('product/duplicate/{id}', 'ProductController@duplicate')->name('product.duplicate');
        Route::get('product/delete/{id}', 'ProductController@delete')->name('product.delete');
        Route::post('update-product/{id}', 'ProductController@update')->name('product.update');
        Route::get('product/{id}/bids', 'ProductController@productBids')->name('product.bids');
        Route::post('bid/winner', 'ProductController@bidWinner')->name('bid.winner');
        Route::get('product/winners', 'ProductController@productWinner')->name('product.winners');
        Route::post('product/winners/filter_winners_by_event', 'ProductController@filter_winners_by_event')->name('product.winners.filter');
        Route::post('product/winners/edit_caption', 'ProductController@edit_winner_caption')->name('product.winners.edit_caption');
        Route::post('product/delivered', 'ProductController@deliveredProduct')->name('product.delivered');
        Route::get('product/{id}/undo', 'ProductController@undoBid')->name('product.undo');
        Route::get('product/{scope}/filterbyevent', 'ProductController@filter_by_event')->name('product.filter_by_event');
        Route::get('products/search', 'ProductController@index')->name('product.search');
        Route::get('/product/import/{uuid?}', [\App\Http\Controllers\Admin\ProductController::class, "import"])->name('product.import');
        Route::post('import-product-from-csv', [\App\Http\Controllers\Admin\ProductController::class, "importProductFromCsv"])
            ->name('product.import-product-from-csv');
        Route::get('imported_products/logs/{uuid}/{option?}', [\App\Http\Controllers\Admin\ProductController::class, "get_log_file"])->name('product.get_log_file');
        Route::get('download_template', 'ProductController@download_template')->name('product.template.download');

        Route::get('/offer/import/{uuid?}', [\App\Http\Controllers\Admin\OfferController::class, "import"])->name('offer.import');
        Route::post('import-offer-from-csv', [\App\Http\Controllers\Admin\OfferController::class, "importOfferFromCsv"])
            ->name('offer.import-offer-from-csv');
        Route::get('imported_offers/logs/{uuid}/{option?}', [\App\Http\Controllers\Admin\OfferController::class, "get_log_file"])->name('offer.get_log_file');
        Route::get('download_template_offer', 'OfferController@download_template')->name('offer.template.download');

        //Manage Events
        Route::get('events/all/{type?}', 'EventController@index')->name('event.index');
        Route::get('events/add', 'EventController@create')->name('event.create');
        Route::get('events/duplicate/{id}', 'EventController@duplicate')->name('event.duplicate');
        Route::get('events/delete/{id}', 'EventController@delete')->name('event.delete');
        Route::post('store-event', 'EventController@store')->name('event.store');
        Route::get('create-test-event', 'EventController@create_test_event')->name('event.create_test');
        Route::post('store-test-event', 'EventController@store_test_event')->name('event.store_test');
        Route::get('event/edit/{id}', 'EventController@edit')->name('event.edit');
        Route::post('update-event/{id}', 'EventController@update')->name('event.update');
        Route::get('end-event/{id}/{agree_end_event?}', 'EventController@endEvent')->name('event.end');
        Route::get('end-event-check/{id}', 'EventController@checkIfAllProductHasBid')->name('event.checkIfAllProductHasBid');
        Route::get('set-end-date/{id}', 'EventController@set_end_date')->name('event.start');
        Route::get('events/search', 'EventController@search')->name('event.search');

        //Orders
        Route::get('orders/all', 'OrderController@index')->name('order.index');
        Route::get('orders/edit/{id}', 'OrderController@edit')->name('order.edit');
        Route::post('orders/update/{id}', 'OrderController@update')->name('order.update');
        Route::post('orders/get_cart_view', 'CartController@getCartIconView')->name('cart.icon.get');
        if (config('app.COMMERCE_MODE') == 1) {
            //commerce
            Route::get('offers/all', 'OfferController@index')->name('offer.index');
            Route::get('offers/live', 'OfferController@index')->name('offer.live');
            Route::get('offers/add/{id?}', 'OfferController@create')->name('offer.create');
            Route::post('store-offer', 'OfferController@store')->name('offer.store');
            Route::get('offer/edit/{id}', 'OfferController@edit')->name('offer.edit');
            Route::get('offer/duplicate/{id}', 'OfferController@duplicate')->name('offer.duplicate');
            Route::get('offer/delete/{id}', 'OfferController@delete')->name('offer.delete');
            Route::post('update-offer/{id}', 'OfferController@update')->name('offer.update');

core/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'address' => 'object',
        'ver_code_send_at' => 'datetime'
    ];

    protected $data = [
        'data'=>1
    ];




    public function login_logs()
    {
        return $this->hasMany(UserLogin::class);
    }

   public function products()
    {
       return $this->belongsToMany(Product::class,'user_events')
    	->withPivot('event_id','is_active')->withTimestamps();//->where('user_events.is_active',1);
    }

    public function groups()
    {
       return $this->belongsToMany(Group::class,'invitations')
    	->withPivot('status','invitation_type')->withTimestamps();
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class)->orderBy('id','desc');
    }

    public function deposits()
    {
        return $this->hasMany(Deposit::class)->where('status','!=',0);
    }

    public function bids()
    {
        return $this->hasMany(Bid::class);
    }

    public function autobidsettings()
    {
        return $this->hasMany(AutoBidSetting::class);
    }

    public function permissiongroups()
    {
        return $this->belongsToMany(PermissionGroup::class , 'user_permission_group', 'user_id', 'group_id')
        ->withTimestamps();
    }

    public function permissionuser(){
        return $this->belongsTo(UserPermission::class,'user_id','id');
    }

    // SCOPES

    public function getFullnameAttribute()
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function scopeActive()
    {
        return $this->where('status', 1);
    }

    public function scopeBanned()
    {
        return $this->where('status', 0);
    }

    public function scopeEmailUnverified()
    {
        return $this->where('ev', 0);
    }

    public function scopeSmsUnverified()
    {
        return $this->where('sv', 0);
    }
    public function scopeEmailVerified()
    {
        return $this->where('ev', 1);
    }

    public function scopeSmsVerified()
    {
        return $this->where('sv', 1);
    }
    public function country(){
        return $this->hasOne(Country::class,'id','billing_country');
    }
    public function country_shipping(){
        return $this->hasOne(Country::class,'id','shipping_country');
    }
    public function userRequestsPendingTermsAccept()
    {
        return $this->hasMany(UserRequest::class,'user_id','id')->where('status',1)->where('terms_accept',0);
    }
    public function userRequestsPendingTermsAcceptArray()
    {
        return $this->userRequestsPendingTermsAccept()->pluck('event_id')->toArray();
    }
    public function userRequestsPendingApproval()
    {
        return $this->hasMany(UserRequest::class,'user_id','id')->where('status',-1);
    }
    public function userRequestsPendingApprovalArray()
    {
        return $this->userRequestsPendingApproval()->pluck('event_id')->toArray();
    }

    public function events(){

        return $this->belongsToMany(Event::class,'user_requests')->where('user_requests.status',1)->withPivot(['date_accept']);
    }
    public function orders()
    {
        return $this->hasMany(Order::class);
    }


}

core/resources/views/admin/product/import.blade.php
@extends('admin.layouts.app')
@section('panel')
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <form action="{{ route('admin.product.import-product-from-csv') }}" method="POST"
                      enctype="multipart/form-data">
                    @csrf
                    <div class="card-body">

                        {{--                                <div class="form-group">--}}
                        {{--                                    <label class="font-weight-bold">@lang('Image') <span class="text-danger">*</span></label>--}}
                        {{--                                    <div class="thumb">--}}
                        {{--                                        <div class="avatar-preview">--}}
                        {{--                                            <div class="profilePicPreview" style="background-image: url('{{getImage(imagePath()['product']['path'],imagePath()['product']['size'])}}')"></div>--}}
                        {{--                                        </div>--}}
                        {{--                                        <div class="avatar-edit">--}}
                        {{--                                            <input type="file" name="image" class="profilePicUpload" id="image" accept=".png, .jpg, .jpeg"/>--}}
                        {{--                                            <label for="image" class="bg--primary"><i class="la la-pencil"></i></label>--}}
                        {{--                                        </div>--}}
                        {{--                                    </div>--}}
                        {{--                                </div>--}}
                        <input type="hidden" name="uuid" id="uuid" value="{{Str::uuid()}}">
                        <input type="file" name="csv_file" id="csv_file" required>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn--primary btn-block"
                                style="margin-top:-15px;">@lang('Submit')</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection


@push('breadcrumb-plugins')

    <a href="{{ route('admin.product.template.download') }}" class="btn btn-sm btn--primary box--shadow1 text--small"><i
            class="la la-fw la-download"></i> @lang('Download Template') </a>
    <a href="{{ route('admin.product.index') }}" class="btn btn-sm btn--primary box--shadow1 text--small"><i
            class="la la-fw la-backward"></i> @lang('Go Back') </a>
@endpush

core/resources/views/admin/product/product_bids.blade.php
@extends('admin.layouts.app')
@section('panel')
<div class="card b-radius--10 ">
    <div class="card-body p-0">
        <div class="table-responsive--md  table-responsive">
            <table class="table table--light style--two">
                <thead>
                <tr>
                    <th>@lang('S.N.')</th>
                    <th>@lang('User Name')</th>
                    <th>@lang('Amount')</th>
                    <th>@lang('Bid Time')</th>
                    <th>@lang('Action')</th>
                </tr>
                </thead>
                <tbody>
                @forelse($bids as $bid)
                <tr>
                    <td data-label="@lang('S.N')">{{ $bids->firstItem() + $loop->index }}</td>
                    <td data-label="@lang('User Name')">{{ $bid->user->fullname }} <br>
                        @php $bidId = $bid->winner ? $bid->winner->bid_id : ''; @endphp
                        @if ($bid->id == $bidId)
                            <span class="badge badge--success">@lang('Winner')</span>
                        @endif
                    </td>
                    <td data-label="@lang('Amount')">{{ $general->cur_sym }}{{ showAmount($bid->amount) }}</td>
                    <td data-label="@lang('Bid Time')">{{ showDateTime($bid->updated_at) }} <br> {{ diffForHumans($bid->updated_at) }}</td>
                    <td data-label="@lang('Action')">
                        <button type="button" class="icon-btn bid-details" data-toggle="tooltip" data-original-title="@lang('Details')"
                            data-bid_id="{{ $bid->id }}"
                            data-product_name="{{ $bid->product->name}}"
                            data-product_price="{{ $general->cur_sym }}{{ showAmount($bid->product->price) }}"
                            data-user_name="{{ $bid->user->fullname}}"
                            data-date_time="{{ showDateTime($bid->updated_at) }}"
                            data-amount="{{ $general->cur_sym }}{{ showAmount($bid->amount) }}"
                            >
                            <i class="las la-desktop text--shadow"></i>
                        </button>
                    </td>
                </tr>
                @empty
                    <tr>
                        <td class="text-muted text-center" colspan="100%">{{ $emptyMessage }}</td>
                    </tr>
                @endforelse

                </tbody>
            </table><!-- table end -->
        </div>
    </div>
    @if ($bids->hasPages())
        <div class="card-footer py-4">
            {{ paginateLinks($bids) }}
        </div>
    @endif
</div>

{{-- BId modal --}}
<div id="bidModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@lang('Bid Details')</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('admin.bid.winner') }}" method="POST">
                @csrf
                <div class="modal-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @lang('Product Name'):
                            <span class="product-name"></span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @lang('Product Price'):
                            <span class="product-price"></span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @lang('Bid User Name'):
                            <span class="bid-user-name"></span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @lang('Bid Amount')
                            <span class="bid-amount"></span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            @lang('Bid Time')
                            <span class="bid-date-time"></span>
                        </li>
                    </ul>
                   <input type="hidden" name="bid_id">
                </div>
                <div class="modal-footer">
                    {{--<button type="submit" class="btn btn--primary btn-block">@lang('Make Winner')</button>--}}
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('breadcrumb-plugins')
<a href="{{ route('admin.product.undo', $product_id) }}" class="btn btn-sm btn--primary box--shadow1 text--small float-sm-left"> @lang('Undo') </a>
<a href="{{ route('admin.product.index') }}" class="btn btn-sm btn--primary box--shadow1 text--small"><i class="la la-fw la-backward"></i> @lang('Go Back') </a>
<a class="btn btn-sm btn--primary box--shadow1 text--small" href="{{route('admin.product.bid.export',$product_id)}}" id="export" onclick="exportTasks(event.target);"><i class="fa fa-fw fa-file-export"></i>@lang('Export to CSV')</a>
@endpush

@push('script')
    <script>
        (function ($) {
            "use strict";
            $('.bid-details').click(function(){
                var modal = $('#bidModal');
                var data = $(this).data();
                modal.find('.product-name').text(data.product_name);
                modal.find('.product-price').text(data.product_price);
                modal.find('.bid-user-name').text(data.user_name);
                modal.find('.bid-date-time').text(data.date_time);
                modal.find('.bid-amount').text(data.amount);
                modal.find('input[name=bid_id]').val(data.bid_id);
                modal.modal('show');
            })

            $('#bidModal').on('hidden.bs.modal', function () {
                $('#bidModal form')[0].reset();
            });


        })(jQuery);
        function exportTasks(_this) {
        let _url = $(_this).data('href');
        window.location.href = _url;
        }
    </script>
@endpush