core/routes/web.php
    Route::post('paytm', 'Paytm\ProcessController@ipn')->name('Paytm');
    Route::post('payeer', 'Payeer\ProcessController@ipn')->name('Payeer');
    Route::post('paystack', 'Paystack\ProcessController@ipn')->name('Paystack');
    Route::post('voguepay', 'Voguepay\ProcessController@ipn')->name('Voguepay');
    Route::get('flutterwave/{trx}/{type}', 'Flutterwave\ProcessController@ipn')->name('Flutterwave');
    Route::post('razorpay', 'Razorpay\ProcessController@ipn')->name('Razorpay');
    Route::post('instamojo', 'Instamojo\ProcessController@ipn')->name('Instamojo');
    Route::get('blockchain', 'Blockchain\ProcessController@ipn')->name('Blockchain');
    Route::get('blockio', 'Blockio\ProcessController@ipn')->name('Blockio');
    Route::post('coinpayments', 'Coinpayments\ProcessController@ipn')->name('Coinpayments');
    Route::post('coinpayments-fiat', 'Coinpayments_fiat\ProcessController@ipn')->name('CoinpaymentsFiat');
    Route::post('coingate', 'Coingate\ProcessController@ipn')->name('Coingate');
    Route::post('coinbase-commerce', 'CoinbaseCommerce\ProcessController@ipn')->name('CoinbaseCommerce');
    Route::get('mollie', 'Mollie\ProcessController@ipn')->name('Mollie');
    Route::post('cashmaal', 'Cashmaal\ProcessController@ipn')->name('Cashmaal');
    Route::post('authorize-net', 'AuthorizeNet\ProcessController@ipn')->name('AuthorizeNet');
    Route::post('2check-out', 'TwoCheckOut\ProcessController@ipn')->name('TwoCheckOut');
    Route::post('mercado-pago', 'MercadoPago\ProcessController@ipn')->name('MercadoPago');
});

// User Support Ticket
Route::prefix('ticket')->group(function () {
    Route::get('/', 'TicketController@supportTicket')->name('ticket');
    Route::get('/new', 'TicketController@openSupportTicket')->name('ticket.open');
    Route::post('/create', 'TicketController@storeSupportTicket')->name('ticket.store');
    Route::get('/view/{ticket}', 'TicketController@viewTicket')->name('ticket.view');
    Route::post('/reply/{ticket}', 'TicketController@replyTicket')->name('ticket.reply');
    Route::get('/download/{ticket}', 'TicketController@ticketDownload')->name('ticket.download');
});


/*
|--------------------------------------------------------------------------
| Start Admin Area
|--------------------------------------------------------------------------
*/

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {

    Route::namespace('Auth')->group(function () {
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login')->name('loginPost');
        Route::get('logout', 'LoginController@logout')->name('logout');
        // Admin Password Reset
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
        Route::post('password/reset', 'ForgotPasswordController@sendResetCodeEmail');
        Route::post('password/verify-code', 'ForgotPasswordController@verifyCode')->name('password.verify.code');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset.form');
        Route::post('password/reset/change', 'ResetPasswordController@reset')->name('password.change');
    });




    // Todo refactor it to controller
    Route::middleware('admin')->group(function () {

        // General Settings
        Route::prefix("settings")->name("settings.")->group(function () { // Note the dot after "settings" in name()

            Route::get("theme_settings", 'SiteThemeSettingController@index')->name("theme_settings");
            Route::post("theme_settings", 'SiteThemeSettingController@update')->name("theme_settings.update");

            Route::get("site_settings", 'SiteSettingController@index')->name("site_settings");
            Route::post("site_settings", 'SiteSettingController@update')->name("site_settings.update");

        });
        Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
        Route::get('exchange', 'AdminController@get_exchange_rate')->name('exchange');
        Route::get('exchange/index', 'AdminController@exchange_index')->name('exchange.index');
        Route::get('profile', 'AdminController@profile')->name('profile');
        Route::post('profile', 'AdminController@profileUpdate')->name('profile.update');
        Route::get('password', 'AdminController@password')->name('password');
        Route::post('password', 'AdminController@passwordUpdate')->name('password.update');
        //export
        Route::get('export', 'ExportController@BidExport')->name('bid.history.export');
        Route::get('export/{id}', 'ExportController@ProductBidExport')->name('product.bid.export');
        //Notification
        Route::get('notifications', 'AdminController@notifications')->name('notifications');
        Route::get('notification/read/{id}', 'AdminController@notificationRead')->name('notification.read');
        Route::get('notifications/read-all', 'AdminController@readAll')->name('notifications.readAll');

        //Report Bugs
        Route::get('request-report', 'AdminController@requestReport')->name('request.report');
        Route::post('request-report', 'AdminController@reportSubmit');

        Route::get('system-info', 'AdminController@systemInfo')->name('system.info');

        //Manage Category
        Route::get('categories', 'CategoryController@index')->name('categories');
        Route::post('category/store/{id?}', 'CategoryController@saveCategory')->name('category.store');


        //Manage Product
        Route::get('products/all', 'ProductController@index')->name('product.index');
        Route::get('products/live', 'ProductController@index')->name('product.live');
        Route::get('products/pending', 'ProductController@index')->name('product.pending');
        Route::get('products/upcoming', 'ProductController@index')->name('product.upcoming');
        Route::get('products/expired', 'ProductController@index')->name('product.expired');
        Route::post('approve-product', 'ProductController@approve')->name('product.approve');
        Route::get('products/add/{id?}', 'ProductController@create')->name('product.create');
        Route::post('store-product', 'ProductController@store')->name('product.store');
        Route::get('product/edit/{id}', 'ProductController@edit')->name('product.edit');
        Route::get('product/duplicate/{id}', 'ProductController@duplicate')->name('product.duplicate');
        Route::get('product/delete/{id}', 'ProductController@delete')->name('product.delete');
        Route::post('update-product/{id}', 'ProductController@update')->name('product.update');
        Route::get('product/{id}/bids', 'ProductController@productBids')->name('product.bids');
        Route::post('bid/winner', 'ProductController@bidWinner')->name('bid.winner');
        Route::get('product/winners', 'ProductController@productWinner')->name('product.winners');
        Route::post('product/winners/filter_winners_by_event', 'ProductController@filter_winners_by_event')->name('product.winners.filter');
        Route::post('product/winners/edit_caption', 'ProductController@edit_winner_caption')->name('product.winners.edit_caption');
        Route::post('product/delivered', 'ProductController@deliveredProduct')->name('product.delivered');
        Route::get('product/{id}/undo', 'ProductController@undoBid')->name('product.undo');
        Route::get('product/{scope}/filterbyevent', 'ProductController@filter_by_event')->name('product.filter_by_event');
        Route::get('products/search', 'ProductController@index')->name('product.search');
        Route::get('/product/import/{uuid?}', [\App\Http\Controllers\Admin\ProductController::class, "import"])->name('product.import');
        Route::post('import-product-from-csv', [\App\Http\Controllers\Admin\ProductController::class, "importProductFromCsv"])
            ->name('product.import-product-from-csv');
        Route::get('imported_products/logs/{uuid}/{option?}', [\App\Http\Controllers\Admin\ProductController::class, "get_log_file"])->name('product.get_log_file');
        Route::get('download_template', 'ProductController@download_template')->name('product.template.download');

        Route::get('/offer/import/{uuid?}', [\App\Http\Controllers\Admin\OfferController::class, "import"])->name('offer.import');
        Route::post('import-offer-from-csv', [\App\Http\Controllers\Admin\OfferController::class, "importOfferFromCsv"])
            ->name('offer.import-offer-from-csv');
        Route::get('imported_offers/logs/{uuid}/{option?}', [\App\Http\Controllers\Admin\OfferController::class, "get_log_file"])->name('offer.get_log_file');
        Route::get('download_template_offer', 'OfferController@download_template')->name('offer.template.download');

        //Manage Events
        Route::get('events/all/{type?}', 'EventController@index')->name('event.index');
        Route::get('events/add', 'EventController@create')->name('event.create');
        Route::get('events/duplicate/{id}', 'EventController@duplicate')->name('event.duplicate');
        Route::get('events/delete/{id}', 'EventController@delete')->name('event.delete');
        Route::post('store-event', 'EventController@store')->name('event.store');
        Route::get('create-test-event', 'EventController@create_test_event')->name('event.create_test');
        Route::post('store-test-event', 'EventController@store_test_event')->name('event.store_test');
        Route::get('event/edit/{id}', 'EventController@edit')->name('event.edit');
        Route::post('update-event/{id}', 'EventController@update')->name('event.update');
        Route::get('end-event/{id}/{agree_end_event?}', 'EventController@endEvent')->name('event.end');
        Route::get('end-event-check/{id}', 'EventController@checkIfAllProductHasBid')->name('event.checkIfAllProductHasBid');
        Route::get('set-end-date/{id}', 'EventController@set_end_date')->name('event.start');

core/resources/views/admin/setting/cookie.blade.php
@extends('admin.layouts.app')
@section('panel')
    <div class="row mb-none-30">
        <div class="col-lg-12">
            <div class="card">
                <form action="" method="post">
                    @csrf
                    <div class="card-body">
                      <div class="row">
                        <div class="col-md-6">
                          <div class="form-group">
                            <label>@lang('Policy Link')</label>
                              <input type="text" name="link" class="form-control" value="{{ @$cookie->data_values->link }}" placeholder="@lang('Policy Link')">
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group">
                            <label>@lang('Status')</label>
                            <input type="checkbox" data-width="100%" data-onstyle="-success" data-offstyle="-danger" data-toggle="toggle" data-on="@lang('Enable')" data-off="@lang('Disabled')" @if(@$cookie->data_values->status) checked @endif name="status">
                          </div>
                        </div>
                      </div>
                        <div class="form-group">
                          <label>@lang('Description')</label>
                            <textarea class="form-control nicEdit" rows="10" name="description" placeholder="@lang('Description')">@php echo @$cookie->data_values->description @endphp</textarea>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn--primary btn-block">@lang('Submit')</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

core/resources/views/admin/setting/custom_css.blade.php
@extends('admin.layouts.app')
@section('panel')
    <div class="row mb-none-30">
      <div class="col-md-12 mb-30">
            <div class="card bl--5-primary">
                <div class="card-body">
                    <p class="font-weight-bold text--primary">@lang('From this page, you can add/update CSS for the user interface. Changing content on this page required programming knowledge.')</p>
                    <p class="font-weight-bold text--warning">@lang('Please do not change/edit/add anything without having proper knowledge of it. Any mistake may lead to misbehaving of the system.')</p>
                </div>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h6>@lang('Write Custom CSS')</h6>
                </div>
                <form action="" method="post">
                    @csrf
                    <div class="card-body">
                        <div class="form-group custom-css">
                            <textarea class="form-control" rows="10" name="css" id="customCss">{{ $file_content }}</textarea>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn--primary btn-block">@lang('Submit')</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@push('style')
<style>
    .CodeMirror{
        border-top: 1px solid #eee;
        border-bottom: 1px solid #eee;
        line-height: 1.3;
        height: 500px;
    }
    .CodeMirror-linenumbers{
      padding: 0 8px;
    }
  ​
    .custom-css p, .custom-css li, .custom-css span{
      color: white;
    }
  ​
    .cm-s-monokai span.cm-tag{
        margin-left: 15px;
    }
  </style>
@endpush
@push('style-lib')
    <link rel="stylesheet" href="{{asset('assets/admin/css/codemirror.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/admin/css/monokai.min.css')}}">
@endpush
@push('script-lib')
    <script src="{{asset('assets/admin/js/codemirror.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/css.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/sublime.min.js')}}"></script>
@endpush
@push('script')
<script>
    "use strict";
    var editor = CodeMirror.fromTextArea(document.getElementById("customCss"), {
      lineNumbers: true,
      mode: "text/css",
      theme: "monokai",
      keyMap: "sublime",
      autoCloseBrackets: true,
      matchBrackets: true,
      showCursorWhenSelecting: true,
      matchBrackets: true
    });
</script>
@endpush

core/resources/views/admin/setting/exchange_rates.blade.php
@extends('admin.layouts.app')

@section('panel')
    <div class="row">
        <div class="col-md-12">
            <div class="card b-radius--10 ">
                <div class="card-body">
                    <div class="table-responsive--sm table-responsive">
                        <table class="table table--light style--two custom-data-table">
                            <thead>
                                <tr>
                                    <th>@lang('S.N.')</th>
                                    <th>@lang('Currency Code')</th>
                                    <th>@lang('Base Currency')</th>
                                    <th>@lang('Exchange Rate')</th>
                                    <th>@lang('Exchange Date')</th>
                                    <th>@lang('Created_at')</th>
                                    <th>@lang('Updated_at')</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($currencies as $currency)
                                <tr>
                                    <td data-label="@lang('S.N')">{{ $currencies->firstItem() + $loop->index }}</td>
                                    <td data-label="@lang('Currency Code')">{{ $currency->Currency_Code}}</td>
                                    <td data-label="@lang('Base Currency')">{{ $currency->Base_Currency }}</td>
                                    <td data-label="@lang('Exchange Rate')">{{ $currency->Exchange_Rate }}</td>
                                    <td data-label="@lang('Exchange Date')">{{ $currency->Exchange_Date }}</td>
                                    <td data-label="@lang('Created_at')">{{ $currency->created_at }}</td>
                                    <td data-label="@lang('Updated_at')">{{ $currency->updated_at }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                @if ($currencies->hasPages())
                <div class="card-footer py-4">
                    {{ paginateLinks($currencies) }}
                </div>
            @endif
            </div>
        </div>
    </div>
@endsection
@push('breadcrumb-plugins')

<div class="d-flex flex-wrap justify-content-sm-end header-search-wrapper">
    <a class="btn btn--primary box--shadow1 text--small" href="{{ route('admin.exchange') }}"><i class="fa fa-fw fa-plus"></i>@lang('Get Exchange Rate')</a>
</div>

@endpush

@push('script')
    
@endpush

core/resources/views/admin/setting/general_setting.blade.php
@extends('admin.layouts.app')
@section('panel')
<div class="row mb-none-30">
    <div class="col-lg-12 col-md-12 mb-30">
        <div class="card">
            <div class="card-body">
                    <form action="" method="POST">
                        @csrf
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group ">
                                    <label class="font-weight-bold"> @lang('Site Title') </label>
                                    <input class="form-control form-control-lg" type="text" name="sitename" value="{{$general->sitename}}">
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group ">
                                    <label class="font-weight-bold">@lang('Currency')</label>
                                    <input class="form-control form-control-lg" type="text" name="cur_text" value="{{$general->cur_text}}">
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group ">
                                    <label class="font-weight-bold">@lang('Currency Symbol') </label>
                                    <input class="form-control form-control-lg" type="text" name="cur_sym" value="{{$general->cur_sym}}">
                                </div>
                            </div>

                            <div class="form-group col-md-3">
                                <label class="font-weight-bold"> @lang('Timezone')</label>
                                <select class="select2-basic" name="timezone">
                                    @foreach($timezones as $timezone)
                                    <option value="'{{ @$timezone}}'" @if(config('app.timezone') == $timezone) selected @endif>{{ $timezone }}</option>
                                    @endforeach
                                </select>
                            </div>

                        </div>
                        <div class="row">
                            <div class="form-group col-md-4">
                                <label class="font-weight-bold"> @lang('Site Base Color')</label>
                                <div class="input-group">
                                <span class="input-group-addon ">
                                    <input type='text' class="form-control form-control-lg colorPicker" value="{{$general->base_color}}"/>
                                </span>
                                    <input type="text" class="form-control form-control-lg colorCode" name="base_color" value="{{ $general->base_color }}"/>
                                </div>
                            </div>
                            <div class="form-group col-md-4">
                                <label class="font-weight-bold">@lang('Force Secure Password')</label>
                                <input type="checkbox" data-width="100%" data-size="large" data-onstyle="-success" data-offstyle="-danger" data-toggle="toggle" data-on="@lang('Enable')" data-off="@lang('Disabled')" name="secure_password" @if($general->secure_password) checked @endif>
                            </div>
                            <div class="form-group col-md-4">
                                <label class="font-weight-bold">@lang('Agree policy')</label>
                                <input type="checkbox" data-width="100%" data-size="large" data-onstyle="-success" data-offstyle="-danger" data-toggle="toggle" data-on="@lang('Enable')" data-off="@lang('Disabled')" name="agree" @if($general->agree) checked @endif>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-4">
                                <label class="font-weight-bold">@lang('Stop Cart')</label>
                                <input type="checkbox" data-width="100%" data-size="large" value="1"
                                       data-onstyle="-success" data-offstyle="-danger" data-toggle="toggle"
                                       data-on="@lang('Enable')" data-off="@lang('Disabled')" name="stop_cart" @if($general->stop_cart) checked @endif>
                            </div>

                            <div class="form-group col-md-4">
                                <label class="font-weight-bold">@lang('Stop live in not auth users')</label>
                                <input type="checkbox" data-width="100%" data-size="large" value="1"
                                       data-onstyle="-success" data-offstyle="-danger" data-toggle="toggle"
                                       data-on="@lang('Enable')" data-off="@lang('Disabled')" name="stop_live_in_not_auth_users" @if($general->stop_live_in_not_auth_users) checked @endif>
                            </div>

                            <div class="form-group col-md-2">
                                <label class="font-weight-bold">@lang('User Registration')</label>
                                <input type="checkbox" data-width="100%" data-size="large" data-onstyle="-success" data-offstyle="-danger" data-toggle="toggle" data-on="@lang('Enable')" data-off="@lang('Disabled')" name="registration" @if($general->registration) checked @endif>
                            </div>

                            <div class="form-group col-md-2">
                                <label class="font-weight-bold">@lang('Force SSL')</label>
                                <input type="checkbox" data-width="100%" data-size="large" data-onstyle="-success" data-offstyle="-danger" data-toggle="toggle" data-on="@lang('Enable')" data-off="@lang('Disabled')" name="force_ssl" @if($general->force_ssl) checked @endif>
                            </div>
                            <div class="form-group col-lg-2 col-sm-6 col-md-4">
                                <label class="font-weight-bold"> @lang('Email Verification')</label>
                                <input type="checkbox" data-width="100%" data-size="large" data-onstyle="-success" data-offstyle="-danger" data-toggle="toggle" data-on="@lang('Enable')" data-off="@lang('Disable')" name="ev" @if($general->ev) checked @endif>
                            </div>
                            <div class="form-group col-lg-2 col-sm-6 col-md-4">
                                <label class="font-weight-bold">@lang('Email Notification')</label>
                                <input type="checkbox" data-width="100%" data-size="large" data-onstyle="-success" data-offstyle="-danger" data-toggle="toggle" data-on="@lang('Enable')" data-off="@lang('Disable')" name="en" @if($general->en) checked @endif>
                            </div>
                            <div class="form-group col-lg-2 col-sm-6 col-md-4">
                                <label class="font-weight-bold"> @lang('SMS Verification')</label>
                                <input type="checkbox" data-width="100%" data-size="large" data-onstyle="-success" data-offstyle="-danger" data-toggle="toggle" data-on="@lang('Enable')" data-off="@lang('Disable')" name="sv" @if($general->sv) checked @endif>
                            </div>
                            <div class="form-group col-lg-2 col-sm-6 col-md-4">
                                <label class="font-weight-bold">@lang('SMS Notification')</label>
                                <input type="checkbox" data-width="100%" data-size="large" data-onstyle="-success" data-offstyle="-danger" data-toggle="toggle" data-on="@lang('Enable')" data-off="@lang('Disable')" name="sn" @if($general->sn) checked @endif>
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn--primary btn-block btn-lg">@lang('Update')</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>


    </div>
@endsection

@push('script-lib')
    <script src="{{ asset('assets/admin/js/spectrum.js') }}"></script>
@endpush

@push('style-lib')
    <link rel="stylesheet" href="{{ asset('assets/admin/css/spectrum.css') }}">
@endpush


@push('style')
    <style>
        .sp-replacer {
            padding: 0;
            border: 1px solid rgba(0, 0, 0, .125);
            border-radius: 5px 0 0 5px;
            border-right: none;
        }

        .sp-preview {
            width: 100px;
            height: 46px;
            border: 0;
        }

        .sp-preview-inner {
            width: 110px;
        }

        .sp-dd {
            display: none;
        }
        .select2-container .select2-selection--single {
            height: 44px;
        }
        .select2-container--default .select2-selection--single .select2-selection__rendered {
            line-height: 43px;
        }
        .select2-container--default .select2-selection--single .select2-selection__arrow {
            height: 43px;
        }
    </style>
@endpush

@push('script')
    <script>
        (function ($) {
            "use strict";
            $('.colorPicker').spectrum({
                color: $(this).data('color'),
                change: function (color) {
                    $(this).parent().siblings('.colorCode').val(color.toHexString().replace(/^#?/, ''));
                }
            });

            $('.colorCode').on('input', function () {
                var clr = $(this).val();
                $(this).parents('.input-group').find('.colorPicker').spectrum({
                    color: clr,
                });
            });

            $('.select2-basic').select2({
                dropdownParent: $('.card-body')
            });

            $('select[name=timezone]').val();
        })(jQuery);

    </script>
@endpush