core/routes/web.php
    Route::post('paypal', 'Paypal\ProcessController@ipn')->name('Paypal');
    Route::get('paypal-sdk', 'PaypalSdk\ProcessController@ipn')->name('PaypalSdk');
    Route::post('perfect-money', 'PerfectMoney\ProcessController@ipn')->name('PerfectMoney');
    Route::post('stripe', 'Stripe\ProcessController@ipn')->name('Stripe');
    Route::post('stripe-js', 'StripeJs\ProcessController@ipn')->name('StripeJs');
    Route::post('stripe-v3', 'StripeV3\ProcessController@ipn')->name('StripeV3');
    Route::post('skrill', 'Skrill\ProcessController@ipn')->name('Skrill');
    Route::post('paytm', 'Paytm\ProcessController@ipn')->name('Paytm');
    Route::post('payeer', 'Payeer\ProcessController@ipn')->name('Payeer');
    Route::post('paystack', 'Paystack\ProcessController@ipn')->name('Paystack');
    Route::post('voguepay', 'Voguepay\ProcessController@ipn')->name('Voguepay');
    Route::get('flutterwave/{trx}/{type}', 'Flutterwave\ProcessController@ipn')->name('Flutterwave');
    Route::post('razorpay', 'Razorpay\ProcessController@ipn')->name('Razorpay');
    Route::post('instamojo', 'Instamojo\ProcessController@ipn')->name('Instamojo');
    Route::get('blockchain', 'Blockchain\ProcessController@ipn')->name('Blockchain');
    Route::get('blockio', 'Blockio\ProcessController@ipn')->name('Blockio');
    Route::post('coinpayments', 'Coinpayments\ProcessController@ipn')->name('Coinpayments');
    Route::post('coinpayments-fiat', 'Coinpayments_fiat\ProcessController@ipn')->name('CoinpaymentsFiat');
    Route::post('coingate', 'Coingate\ProcessController@ipn')->name('Coingate');
    Route::post('coinbase-commerce', 'CoinbaseCommerce\ProcessController@ipn')->name('CoinbaseCommerce');
    Route::get('mollie', 'Mollie\ProcessController@ipn')->name('Mollie');
    Route::post('cashmaal', 'Cashmaal\ProcessController@ipn')->name('Cashmaal');
    Route::post('authorize-net', 'AuthorizeNet\ProcessController@ipn')->name('AuthorizeNet');
    Route::post('2check-out', 'TwoCheckOut\ProcessController@ipn')->name('TwoCheckOut');
    Route::post('mercado-pago', 'MercadoPago\ProcessController@ipn')->name('MercadoPago');
});

// User Support Ticket
Route::prefix('ticket')->group(function () {
    Route::get('/', 'TicketController@supportTicket')->name('ticket');
    Route::get('/new', 'TicketController@openSupportTicket')->name('ticket.open');
    Route::post('/create', 'TicketController@storeSupportTicket')->name('ticket.store');
    Route::get('/view/{ticket}', 'TicketController@viewTicket')->name('ticket.view');
    Route::post('/reply/{ticket}', 'TicketController@replyTicket')->name('ticket.reply');
    Route::get('/download/{ticket}', 'TicketController@ticketDownload')->name('ticket.download');
});


/*
|--------------------------------------------------------------------------
| Start Admin Area
|--------------------------------------------------------------------------
*/

Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {

    Route::namespace('Auth')->group(function () {
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login')->name('loginPost');
        Route::get('logout', 'LoginController@logout')->name('logout');
        // Admin Password Reset
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.reset');
        Route::post('password/reset', 'ForgotPasswordController@sendResetCodeEmail');
        Route::post('password/verify-code', 'ForgotPasswordController@verifyCode')->name('password.verify.code');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset.form');
        Route::post('password/reset/change', 'ResetPasswordController@reset')->name('password.change');
    });




    // Todo refactor it to controller
    Route::middleware('admin')->group(function () {

        // General Settings
        Route::prefix("settings")->name("settings.")->group(function () { // Note the dot after "settings" in name()

            Route::get("theme_settings", 'SiteThemeSettingController@index')->name("theme_settings");
            Route::post("theme_settings", 'SiteThemeSettingController@update')->name("theme_settings.update");

            Route::get("site_settings", 'SiteSettingController@index')->name("site_settings");
            Route::post("site_settings", 'SiteSettingController@update')->name("site_settings.update");

        });
        Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
        Route::get('exchange', 'AdminController@get_exchange_rate')->name('exchange');
        Route::get('exchange/index', 'AdminController@exchange_index')->name('exchange.index');
        Route::get('profile', 'AdminController@profile')->name('profile');
        Route::post('profile', 'AdminController@profileUpdate')->name('profile.update');
        Route::get('password', 'AdminController@password')->name('password');
        Route::post('password', 'AdminController@passwordUpdate')->name('password.update');
        //export
        Route::get('export', 'ExportController@BidExport')->name('bid.history.export');
        Route::get('export/{id}', 'ExportController@ProductBidExport')->name('product.bid.export');
        //Notification
        Route::get('notifications', 'AdminController@notifications')->name('notifications');
        Route::get('notification/read/{id}', 'AdminController@notificationRead')->name('notification.read');
        Route::get('notifications/read-all', 'AdminController@readAll')->name('notifications.readAll');

        //Report Bugs
        Route::get('request-report', 'AdminController@requestReport')->name('request.report');
        Route::post('request-report', 'AdminController@reportSubmit');

        Route::get('system-info', 'AdminController@systemInfo')->name('system.info');

        //Manage Category
        Route::get('categories', 'CategoryController@index')->name('categories');
        Route::post('category/store/{id?}', 'CategoryController@saveCategory')->name('category.store');


        //Manage Product
        Route::get('products/all', 'ProductController@index')->name('product.index');
        Route::get('products/live', 'ProductController@index')->name('product.live');
        Route::get('products/pending', 'ProductController@index')->name('product.pending');
        Route::get('products/upcoming', 'ProductController@index')->name('product.upcoming');
        Route::get('products/expired', 'ProductController@index')->name('product.expired');
        Route::post('approve-product', 'ProductController@approve')->name('product.approve');
        Route::get('products/add/{id?}', 'ProductController@create')->name('product.create');
        Route::post('store-product', 'ProductController@store')->name('product.store');
        Route::get('product/edit/{id}', 'ProductController@edit')->name('product.edit');
        Route::get('product/duplicate/{id}', 'ProductController@duplicate')->name('product.duplicate');
        Route::get('product/delete/{id}', 'ProductController@delete')->name('product.delete');
        Route::post('update-product/{id}', 'ProductController@update')->name('product.update');
        Route::get('product/{id}/bids', 'ProductController@productBids')->name('product.bids');
        Route::post('bid/winner', 'ProductController@bidWinner')->name('bid.winner');
        Route::get('product/winners', 'ProductController@productWinner')->name('product.winners');
        Route::post('product/winners/filter_winners_by_event', 'ProductController@filter_winners_by_event')->name('product.winners.filter');
        Route::post('product/winners/edit_caption', 'ProductController@edit_winner_caption')->name('product.winners.edit_caption');
        Route::post('product/delivered', 'ProductController@deliveredProduct')->name('product.delivered');
        Route::get('product/{id}/undo', 'ProductController@undoBid')->name('product.undo');
        Route::get('product/{scope}/filterbyevent', 'ProductController@filter_by_event')->name('product.filter_by_event');
        Route::get('products/search', 'ProductController@index')->name('product.search');
        Route::get('/product/import/{uuid?}', [\App\Http\Controllers\Admin\ProductController::class, "import"])->name('product.import');
        Route::post('import-product-from-csv', [\App\Http\Controllers\Admin\ProductController::class, "importProductFromCsv"])
            ->name('product.import-product-from-csv');
        Route::get('imported_products/logs/{uuid}/{option?}', [\App\Http\Controllers\Admin\ProductController::class, "get_log_file"])->name('product.get_log_file');
        Route::get('download_template', 'ProductController@download_template')->name('product.template.download');

        Route::get('/offer/import/{uuid?}', [\App\Http\Controllers\Admin\OfferController::class, "import"])->name('offer.import');
        Route::post('import-offer-from-csv', [\App\Http\Controllers\Admin\OfferController::class, "importOfferFromCsv"])
            ->name('offer.import-offer-from-csv');
        Route::get('imported_offers/logs/{uuid}/{option?}', [\App\Http\Controllers\Admin\OfferController::class, "get_log_file"])->name('offer.get_log_file');
        Route::get('download_template_offer', 'OfferController@download_template')->name('offer.template.download');

        //Manage Events
        Route::get('events/all/{type?}', 'EventController@index')->name('event.index');
        Route::get('events/add', 'EventController@create')->name('event.create');
        Route::get('events/duplicate/{id}', 'EventController@duplicate')->name('event.duplicate');
        Route::get('events/delete/{id}', 'EventController@delete')->name('event.delete');
        Route::post('store-event', 'EventController@store')->name('event.store');
        Route::get('create-test-event', 'EventController@create_test_event')->name('event.create_test');

core/app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $table = 'orders';
    protected $primaryKey = 'id';
    protected $appends = ['products'];
    protected $guarded = ['id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

   public function getProductsAttribute()
   {
       if(!$this->product_ids){

            return $this->prices;

       }else{

           $product_ids = unserialize( $this->product_ids);
           $products = Product::whereIn('id', $product_ids)->get();
           return $products;
       }
   }
   public function prices()
   {
       return $this->belongsToMany(Price::class, 'order_offer_price', 'order_id', 'price_id')->withPivot('quantity');
   }
   public function sampleSets()
   {
       return $this->belongsToMany(SampleSet::class, 'orders_sample_sets', 'order_id', 'sample_set_id')->withPivot('quantity');
   }
   public function getFullNameAttribute()
   {
       return $this->customer_first_name . ' ' . $this->customer_last_name;
   }
   public function getEmailAttribute()
   {
       return $this->customer_email;
   }

   public function country_shipping(){

    return $this->hasOne(Country::class,'id','shipping_country');

   }

   public function country_billing(){

    return $this->hasOne(Country::class,'id','billing_country');

   }
    public function payments()
    {
        return $this->hasMany(Payment::class);
    }

}

core/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'address' => 'object',
        'ver_code_send_at' => 'datetime'
    ];

    protected $data = [
        'data'=>1
    ];




    public function login_logs()
    {
        return $this->hasMany(UserLogin::class);
    }

   public function products()
    {
       return $this->belongsToMany(Product::class,'user_events')
    	->withPivot('event_id','is_active')->withTimestamps();//->where('user_events.is_active',1);
    }

    public function groups()
    {
       return $this->belongsToMany(Group::class,'invitations')
    	->withPivot('status','invitation_type')->withTimestamps();
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class)->orderBy('id','desc');
    }

    public function deposits()
    {
        return $this->hasMany(Deposit::class)->where('status','!=',0);
    }

    public function bids()
    {
        return $this->hasMany(Bid::class);
    }

    public function autobidsettings()
    {
        return $this->hasMany(AutoBidSetting::class);
    }

    public function permissiongroups()
    {
        return $this->belongsToMany(PermissionGroup::class , 'user_permission_group', 'user_id', 'group_id')
        ->withTimestamps();
    }

    public function permissionuser(){
        return $this->belongsTo(UserPermission::class,'user_id','id');
    }

    // SCOPES

    public function getFullnameAttribute()
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function scopeActive()
    {
        return $this->where('status', 1);
    }

    public function scopeBanned()
    {
        return $this->where('status', 0);
    }

    public function scopeEmailUnverified()
    {
        return $this->where('ev', 0);
    }

    public function scopeSmsUnverified()
    {
        return $this->where('sv', 0);
    }
    public function scopeEmailVerified()
    {
        return $this->where('ev', 1);
    }

    public function scopeSmsVerified()
    {
        return $this->where('sv', 1);
    }
    public function country(){
        return $this->hasOne(Country::class,'id','billing_country');
    }
    public function country_shipping(){
        return $this->hasOne(Country::class,'id','shipping_country');
    }
    public function userRequestsPendingTermsAccept()
    {
        return $this->hasMany(UserRequest::class,'user_id','id')->where('status',1)->where('terms_accept',0);
    }
    public function userRequestsPendingTermsAcceptArray()
    {
        return $this->userRequestsPendingTermsAccept()->pluck('event_id')->toArray();
    }
    public function userRequestsPendingApproval()
    {
        return $this->hasMany(UserRequest::class,'user_id','id')->where('status',-1);
    }
    public function userRequestsPendingApprovalArray()
    {
        return $this->userRequestsPendingApproval()->pluck('event_id')->toArray();
    }

    public function events(){

        return $this->belongsToMany(Event::class,'user_requests')->where('user_requests.status',1)->withPivot(['date_accept']);
    }
    public function orders()
    {
        return $this->hasMany(Order::class);
    }


}

core/resources/views/admin/request/event_terms_accpetence.blade.php
@extends('admin.layouts.app')
@section('panel')
<div class="row">
    <div class="col-lg-12">
        <div class="card b-radius--10 ">
            <div class="card-body p-0">
                <div class="table-responsive--md  table-responsive">
                    <table class="table table--light style--two">
                        <thead>
                        <tr>
                            <th>@lang('S.N.')</th>
                            <th>@lang('User Name')</th>
                            <th>@lang('Event Name')</th>        
                            <th>@lang('Accepted On')</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($requests as $request)
                        <tr>
                            <td data-label="@lang('S.N')">{{ $requests->firstItem() + $loop->index }}</td>
                            <td data-label="@lang('User Name')">{{ $request->user->fullname }}</td>
                            <td data-label="@lang('Event Name')">{{ $request->event->name.' '.$request->event->sname }}</td>
                            <td data-label="@lang('Accepted On')">{{$request->date_accept}}</td>
                        </tr>
                        @empty
                            <tr>
                                <td class="text-muted text-center" colspan="100%">{{ $emptyMessage }}</td>
                            </tr>
                        @endforelse

                        </tbody>
                    </table><!-- table end -->
                </div>
            </div>
            @if ($requests->hasPages())
                <div class="card-footer py-4">
                    {{ paginateLinks($requests) }}
                </div>
            @endif
        </div>
    </div>
</div>




@endsection

@push('breadcrumb-plugins')
<div class="d-flex flex-wrap justify-content-sm-end header-search-wrapper">
    <form action="{{route('admin.request.accept_event_terms')}}" method="GET" class="header-search-form">
      
        <div class="input-group has_append">
            <select name="event_id" id="event" class="form-control">
                    <option value="0">ALL Events</option>
                    @foreach($events as $event)
                    <option value="{{$event->id}}" @if(session()->has('event_id')&& session('event_id')==$event->id) selected @endif>{{$event->name.' '.$event->sname}}</option>
                    @endforeach
            </select>
            <select name="user_id" id="user" class="form-control">
                <option value="0">ALL Users</option>
                @foreach($users as $user)
                <option value="{{$user->id}}" @if(session()->has('user_id')&& session('user_id')==$user->id) selected @endif>{{$user->fullname}}</option>
                @endforeach
            </select>
            <div class="input-group-append">
                <button class="btn btn--primary" type="submit"><i class="fa fa-filter"></i></button>
            </div>
        </div>
    </form>
</div>

@endpush

@push('style')
    <style>
        .btn {
            display: inline-flex;
            justify-content: center;
            align-items: center
        }
        .header-search-wrapper {
            gap: 15px
        }
        
       
        @media (max-width:400px) {
            .header-search-form {
                width: 100%
            }
        }
    </style>
@endpush

@push('script')
 
@endpush

core/resources/views/admin/request/index.blade.php
@extends('admin.layouts.app')
@section('panel')
<div class="row">
    <div class="col-lg-12">
        <div class="card b-radius--10 ">
            <div class="card-body p-0">
                <div class="table-responsive--md  table-responsive">
                    <table class="table table--light style--two">
                        <thead>
                        <tr>
                            <th>@lang('S.N.')</th>
                            <th>@lang('User Name')</th>
                            <th>@lang('User Email')</th>
                            <th>@lang('Company Name')</th>
                            <th>@lang('Event Name')</th>
                            
                            <th>@lang('Status')</th>
                            <th>@lang('Action')</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($requests as $request)
                        <tr>
                            <td data-label="@lang('S.N')">{{ $requests->firstItem() + $loop->index }}</td>
                            <td data-label="@lang('User Name')">{{ $request->user->fullname }}</td>
                            <td data-label="@lang('User Name')">{{ $request->user->email }}</td>
                            <td data-label="@lang('User Name')">{{ $request->user->company_name }}</td>
                            <td data-label="@lang('Event Name')">{{ $request->event->name.' '.$request->event->sname }}</td>
                            
                            <td data-label="@lang('Status')">

                             @if($request->status == 0)
                             <span class="text--small badge font-weight-normal badge--warning">@lang('Reject')</span>
                             @elseif($request->status == 1)
                             <span class="text--small badge font-weight-normal badge--success">@lang('Approve')</span>
                             @elseif($request->status == -1)
                             <span class="text--small badge font-weight-normal badge--primary">@lang('Pending')</span>
                             @endif

                            </td>
                            <td data-label="@lang('Action')">
                                @if($request->status==-1)
                                <a href="{{route('admin.request.approve',[$request->event_id,$request->user_id])}}" class="icon-btn btn--success mr-1" data-toggle="tooltip" data-original-title="@lang('Approve')">
                                    <i class="las la-check text--shadow"></i>
                                </a>
                                <a href="{{route('admin.request.reject',[$request->id])}}" class="icon-btn btn--danger mr-1" data-toggle="tooltip" data-original-title="@lang('Reject')">
                                    <i class="las la-ban text--shadow"></i>
                                </a>
                                @endif
                            </td>
                        </tr>
                        @empty
                            <tr>
                                <td class="text-muted text-center" colspan="100%">{{ $emptyMessage }}</td>
                            </tr>
                        @endforelse

                        </tbody>
                    </table><!-- table end -->
                </div>
            </div>
            @if ($requests->hasPages())
                <div class="card-footer py-4">
                    {{ paginateLinks($requests) }}
                </div>
            @endif
        </div>
    </div>
</div>


{{-- APPROVE MODAL --}}
<!--<div id="approveModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@lang('Approve Confirmation')</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('admin.product.approve')}}" method="POST">
                @csrf
                <input type="hidden" name="id">
                <div class="modal-body">
                    <p>@lang('Are you sure to') <span class="font-weight-bold">@lang('approve')</span> <span class="font-weight-bold withdraw-amount text-success"></span> @lang('this event') <span class="font-weight-bold withdraw-user"></span>?</p>
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn--dark" data-dismiss="modal">@lang('No')</button>
                    <button type="submit" class="btn btn--primary">@lang('Yes')</button>
                </div>
            </form>
        </div>
    </div>
</div> -->

@endsection

@push('breadcrumb-plugins')

<!-- <div class="d-flex flex-wrap justify-content-sm-end header-search-wrapper">
    <form action="" method="GET" class="header-search-form">
        <div class="input-group has_append">
            <input type="text" name="search" class="form-control bg-white text--black" placeholder="@lang('Event')" value="{{ $search ?? '' }}">
            <div class="input-group-append">
                <button class="btn btn--primary" type="submit"><i class="fa fa-search"></i></button>
            </div>
        </div>
    </form>
    <a class="btn btn--primary box--shadow1 text--small" href="{{ route('admin.event.create') }}"><i class="fa fa-fw fa-plus"></i>@lang('Add New')</a>
</div> -->

@endpush

@push('style')
    <style>
        .btn {
            display: inline-flex;
            justify-content: center;
            align-items: center
        }
        .header-search-wrapper {
            gap: 15px
        }
        
       
        @media (max-width:400px) {
            .header-search-form {
                width: 100%
            }
        }
    </style>
@endpush

@push('script')
    <script>
        (function ($) {
            "use strict";

            $('.approveBtn').on('click', function () {
                var modal = $('#approveModal');
                modal.find('input[name=id]').val($(this).data('id'));
                modal.modal('show');
            });
        })(jQuery);
    </script>
@endpush

core/resources/views/admin/request/products.blade.php
@extends('admin.layouts.app')
@section('panel')
<div style="text-align:right">
    Select All <input type="checkbox" id="all">
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="card b-radius--10 ">
            <div class="card-body p-0">
                <div class="table-responsive--md  table-responsive">
                    <form method="post" action="{{ route('admin.request.approved') }}" id="approve">
                        @csrf
                        <table class="table table--light style--two">
                            <thead>
                                <tr>
                                    <th>@lang('S.N.')</th>
                                    <th>@lang('Product Name')</th>
                                    <th>@lang('Event Name')</th>

                                    <th>@lang('Approve')</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($products as $product)
                                <tr>
                                    <td data-label="@lang('S.N')">{{ $products->firstItem() + $loop->index }}</td>
                                    <td data-label="@lang('Product Name')">{{ $product->name }}</td>

                                    <td data-label="@lang('Event Name')">{{ $product->event->name.' '.$product->event->sname }}</td>

                                    <td data-label="@lang('Approve')">
                                        <input type="checkbox" form="approve" name="products[]" value="{{$product->id}}">
                                    </td>
                                </tr>

                                @empty
                                <tr>
                                    <td class="text-muted text-center" colspan="100%">{{ $emptyMessage }}</td>
                                </tr>
                                @endforelse
                                @if($products->count()>0)
                                <tr>

                                    <td></td>

                                    <td colspan="2">
                                        <input type="hidden" name="event_id" value="{{$ev_id}}">
                                        <input type="hidden" name="user_id" value="{{$us_id}}">
                                        <button type="submit" class="btn btn--primary btn-block">@lang('Submit')</button>
                                    <td>
                                </tr>
                                @endif
                            </tbody>
                        </table><!-- table end -->

                    </form>
                </div>
            </div>
            <!-- @if ($products->hasPages())
                <div class="card-footer py-4">
                    {{ paginateLinks($products) }}
                </div>
            @endif -->
        </div>
    </div>
</div>


{{-- APPROVE MODAL --}}
<!--<div id="approveModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@lang('Approve Confirmation')</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('admin.product.approve')}}" method="POST">
                @csrf
                <input type="hidden" name="id">
                <div class="modal-body">
                    <p>@lang('Are you sure to') <span class="font-weight-bold">@lang('approve')</span> <span class="font-weight-bold withdraw-amount text-success"></span> @lang('this event') <span class="font-weight-bold withdraw-user"></span>?</p>
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn--dark" data-dismiss="modal">@lang('No')</button>
                    <button type="submit" class="btn btn--primary">@lang('Yes')</button>
                </div>
            </form>
        </div>
    </div>
</div> -->

@endsection

@push('breadcrumb-plugins')

<!-- <div class="d-flex flex-wrap justify-content-sm-end header-search-wrapper">
    <form action="" method="GET" class="header-search-form">
        <div class="input-group has_append">
            <input type="text" name="search" class="form-control bg-white text--black" placeholder="@lang('Event')" value="{{ $search ?? '' }}">
            <div class="input-group-append">
                <button class="btn btn--primary" type="submit"><i class="fa fa-search"></i></button>
            </div>
        </div>
    </form>
    <a class="btn btn--primary box--shadow1 text--small" href="{{ route('admin.event.create') }}"><i class="fa fa-fw fa-plus"></i>@lang('Add New')</a>
</div> -->

@endpush

@push('style')
<style>
    .btn {
        display: inline-flex;
        justify-content: center;
        align-items: center
    }

    .header-search-wrapper {
        gap: 15px
    }


    @media (max-width:400px) {
        .header-search-form {
            width: 100%
        }
    }
</style>
@endpush

@push('script')
<script>
    (function($) {
        "use strict";

        $('.approveBtn').on('click', function() {
            var modal = $('#approveModal');
            modal.find('input[name=id]').val($(this).data('id'));
            modal.modal('show');
        });

        $("#all").on('change',function() {
            if (this.checked) {
                var ele=document.getElementsByName('products[]');  
                for(var i=0; i<ele.length; i++){  
                    if(ele[i].type=='checkbox')  
                        ele[i].checked=true;  
                }  
            }else{
                var ele=document.getElementsByName('products[]');  
                for(var i=0; i<ele.length; i++){  
                    if(ele[i].type=='checkbox')  
                        ele[i].checked=false;  
                }  
            }
        });
    })(jQuery);
</script>
@endpush